[package]
name = "daemon-starter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.15", features = ["derive"] }
daemonize = "0.4.1"
libc = "0.2.125"
users = "0.11.0"